"""
Django settings for mysite project.

Generated by 'django-admin startproject' using Django 2.0.

For more information on this file, see
https://docs.djangoproject.com/en/2.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.0/ref/settings/
"""

import os
from .base import *

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '$aq^n))a)+hsapt*sg-*eip8(6fp)ctgu@)xi!6+irni7)$no%'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

# ALLOWED_HOSTS = ['zzzf.pythonanywhere.com']
ALLOWED_HOSTS = []


# Database
# https://docs.djangoproject.com/en/2.0/ref/settings/#databases

'''
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}
'''
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'mysite_db',
        'USER': 'zzzf',
        'PASSWORD': 'abc123456',
        'HOST':'',  # 数据库所在主机。可以设置为空，表示当前主机，也可以用localhost，也代表当前主机
        'PORT': '3306',
    }
}

# 发送邮件设置
# https://docs.djangoproject.com/en/2.0/ref/settings/#email
# https://docs.djangoproject.com/en/2.0/topics/email/
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'   # email相关的默认配置，可写可不写
EMAIL_HOST = 'smtp.qq.com'  # 我们是用qq邮箱进行发送，qq邮箱发送邮件是用到一个SMTP协议，qq邮箱提供的EMAIL_HOST是smtp.qq.com，它通过这个服务器 这个域名去发送
EMAIL_PORT = 25 # 发送邮件提供的端口号是25
EMAIL_HOST_USER = '1248285187@qq.com'  # 邮箱地址
# EMAIL_HOST_PASSWORD = 'dhvbwihfvbuehccc'    # 授权码
EMAIL_HOST_PASSWORD = os.environ['EMAIL_HOST_PASSWORD']    # 授权码
EMAIL_SUBJECT_PREFIX = '[张张张的博客]'   # 发送前缀
EMAIL_USE_TLS = True # 与SMTP服务器通信时，是否启动TLS链接（安全链接）